### ISSUE TITLE
Замечания по CodeReview

### ISSUE THREAD

**Issue by Warboss-rus** [Aleksandrgithub/phpTodoList#1]
1. API создания таска должен быть POST-запросом, который принимает данные в теле, а не в URL. Сейчас могут возникнуть проблемы с урл-кодированием данных при попытке ввести сложный Unicode из браузера.
2. Нужно разделить модель (класс Todo) и работу с БД (сохранение, обновление, удаление, получение, должен работать с моделью).
3. Нужны константы со статусом.
4. Сейчас можно менять статус задач в произвольном порядке и выставить абсолютно любое значение. Лучше сделать отдельный API "Пометить задачу как выполненную", которая кинет ошибку, если задача уже выполнена.
5. Поля в модели (класс Todo) стоит сделать приватными, реализовать геттеры и сеттеры где это нужно
6. При попытке сменить статус несуществующего таска должен выбрасываться статус код 404 или 400.
7. В случае общей ошибки лучше возвращать статус 500, а не 503
8. Из API создания задачи неплохо бы возвращать её Id
9. extract лучше не использовать, явно прописывать ключи (но это должно поправится при вынесении класса для работы с БД.
10. Нужны namespace-ы - модель в одном неймспейсе, работа с базой - в другом, работа с HTTP - в третьем
11. Если в API обновления статуса или удаления отсутствует id, нужно выдавать человекочитаемый текст, который объяснит куда его нужно подставить

**Comment by Aleksandrgithub** [comment]
Привет, ошибки исправил,  с cURL работал через коммандную строку, пока перешёл на латиницу, с namespace'ами осознанно в проекте работал первый раз, надеюсь правильно понял твои требования.

**Comment by Warboss-rus** [comment]
1. OK
2. Сейчас у тебя класс Task практически ничего не делает. Идея в том, чтобы класс Transaction умел только доставать, сохранять и удалять объекты типа Task, а логика по операциям (перевести из статуса в статус, поменять description и т.д.) была в модели. Соответственно в Transaction должны быть тметоды типа create($task), read($id): Task, update($task), delete ($id) и readAll(), а логика markTaskCompleted должна быть либо в самом классе Task, либо в отдельном сервисе, который производит операции над Task-ами
3. Я имел в виду статусы таска. Они должны лежать в модели, рядом с классом Task. Сейчас у тебя есть константа TASK_STATUS, название которой ни о чем не говорит
4. ОК, но см. п.2.
5. Можно добавить конструктор, чтобы было проще работать с классом и проинициализировать поля значениями по-умолчанию. Сейчас к примеру при создании таска он не до конца проинициализирован, т.к. его статус неопределен.
6. Для несуществующего таска выкинется 500, а не 40х
7. ОК
8. ОК
9. ОК
10. Неймспейсы нужны чтобы группировать связанные классы. Также правило хорошего тона - чтобы неймспейс соответствовал структуре папок, т.е. чтобы классы в папке Model имели неймспейс Model, классы в task имели неймспейс task и т.д. Для этого проекта я бы предложил неймспейсы Model, Database и Transport
11. OK

**Comment by Aleksandrgithub** [comment]
Хорошо, исправлю!

**Comment by Aleksandrgithub** [comment]
Ошибки исправил!

**Comment by Warboss-rus** [comment]
2. OK
3. OK
5. OK
6. OK
10. OK
